version: '3.9'
services:
  # MySQL DB
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 9c%7O?PHoj0O
      MYSQL_DATABASE: appdb
    ports:
      - '3306:3306'

  # API
  kanban-api-node:
    depends_on:
      - mysqldb
    container_name: kanban-api-node
    build: ./
    restart: unless-stopped
    command: npm start
    working_dir: /usr/src/kanban-api-node
    environment:
      DB_NAME: appdb
      DB_HOST: mysqldb
      DB_PASSWORD: 9c%7O?PHoj0O
    links:
      - mysqldb
    ports:
      - '3000:3000'
    #volumes:
    #  - ./:/usr/src/kanban-api-node
